#coding=utf-8
REDIS_KEY_UID="VRchat:Online:%s"
REDIS_KEY_WORLD="VRchat:World"
REDIS_KEY_DISCORD_CHANNEL_CONFIG="Discord:Channel:%s"
REDIS_KEY_EXP=90
REDIS_NOTIFICATION_QUEUE='VRchat:MsgQueue'
MSG_TEXT_FORMAT="%-20s %-20s %-20s"
REDIS_HOST='localhost'
REDIS_PORT=6379
LOOP_DELAY=10
REAPER_INTERVAL=600
BOT_LOOP_DELAY=2
PREFIX="!"



